= Features Included in Government Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Government Cloud includes the full functionality of the Anypoint Platform runtime plane (services and Mule runtime engine) and a subset of the Anypoint Platform control plane (browser-based management of APIs and Mule runtime engines) functionality. Government Cloud supports the full API-led connectivity methodology and end-to-end API lifecycle management.

By default, Mule runtime engine is configured to run in FIPS-compliant mode. See xref:mule-runtime::fips-140-2-compliance-support.adoc[FIPS 140-2 Compliance Support] for additional information.

Although Anypoint Studio is not part of Government Cloud, you can use Anypoint Studio offline to build applications to deploy in Government Cloud. See xref:studio::set-credentials-in-studio-to.adoc[Configuring Anypoint Platform Credentials] for additional information.

The following features are included in Government Cloud:

* xref:design-center::index.adoc[Design Center]

** xref:design-center::design-create-publish-api-specs.adoc[API Designer]
** xref:design-center::design-create-publish-api-specs.adoc[Visual API Designer]
** xref:apikit::apikit-console-concept.adoc[API Console]
** xref:design-center::design-mocking-service.adoc[Mocking service]
** xref:exchange::to-create-an-asset.adoc[RAML and OAS support]
* xref:exchange::index.adoc[Exchange]
** xref:api-manager::access-developer-portal-task.adoc[API developer portals]
** xref:design-center::design-mocking-service.adoc[API simulation (mocking service)]
** xref:api-manager::api-notebook-concept.adoc[API Notebooks]
** xref:apikit::apikit-4-generate-workflow.adoc[API testing function]
* *Management Center*
** xref:access-management::index.adoc[*Access management*]
** xref:object-store::osv2-guide.adoc[*Object Store*]
** xref:api-manager::latest-overview-concept.adoc[*API Manager*]
** xref:runtime-manager::index.adoc[*Runtime Manager*]
** xref:runtime-manager::cloudhub.adoc[*CloudHub*]

The following products will be phased into Government Cloud over time:

* xref:api-manager::analytics-landing-page.adoc[Anypoint Analytics] 
* xref:monitoring::index.adoc[Anypoint Monitoring]
* xref:mq::index.adoc[Anypoint MQ]
* xref:anypoint-security::index.adoc[Anypoint Security]
* xref:visualizer::index.adoc[Anypoint Visualizer]
* xref:data-gateway::index.adoc[API Data Gateway]

For a detailed list of components and support for each component by control plane, refer to xref:general/intro-platform-hosting#support-matrix-for-control-plane-hosting-options[Support Matrix for Control Plane Hosting Options].

== See Also

* xref:gov-cloud::gov-cloud-security.adoc[Security in Government Cloud]
* xref:mule-runtime::fips-140-2-compliance-support.adoc[FIPS 140-2 Compliance Support]
