= Features Included in Government Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

MuleSoft Government Cloud includes the full functionality of the Anypoint Platform runtime plane (services and Mule runtime engine) and a subset of the Anypoint Platform control plane (browser-based management of APIs and Mule runtime engine instances) functionality. Government Cloud supports the full API-led connectivity methodology and end-to-end API lifecycle management.

MuleSoft Government Cloud supports Mule runtime engine v3.9 and later.
[IMPORTANT]
====
Because MuleSoft Government Cloud does not support Mule agents with self-signed certificates, specific versions of Mule runtime engine are required:

* Mule 3: v1.12.0 and later
* Mule 4: v2.2.0 and later

For FIPS compliance, Mule 4 version 2.4.9 or later is required.
====

By default, Mule runtime engine is configured to run in FIPS-compliant mode. See xref:mule-runtime::fips-140-2-compliance-support.adoc[FIPS 140-2 Compliance Support] for additional information.

Although Anypoint Studio is not part of Government Cloud, you can use Anypoint Studio offline to build applications to deploy in Government Cloud.

* xref:design-center::index.adoc[Design Center]

** xref:design-center::design-create-publish-api-specs.adoc[API Designer]
** xref:design-center::design-create-publish-api-visual-editor.adoc[Visual API Designer]
** xref:design-center::design-create-publish-api-specs#documenting[API Console]
** xref:design-center::design-create-publish-api-specs#designing[RAML and OAS support]
* xref:exchange::index.adoc[Anypoint Exchange]
** xref:exchange::to-describe-an-asset.adoc[API developer portals]
** xref:exchange::ex2-to-simulate-api-data.adoc[API simulation (mocking service)]
** xref:exchange::about-documenting-an-api.adoc[API Notebooks]
** xref:munit::index.adoc[MUnit]
** xref:apikit::overview-4.adoc[APIKit]
* Management Center
** xref:access-management::index.adoc[Anypoint Access Management]
+
[NOTE]
Some items displayed in the Access Management UI, such as API alerts and analytics information, cannot be accessed or configured.
** xref:object-store::osv2-guide.adoc[Object Store]
** xref:api-manager::latest-overview-concept.adoc[API Manager]
** xref:runtime-manager::index.adoc[Runtime Manager]
** xref:runtime-manager::cloudhub.adoc[CloudHub]
* Standalone deployment of Mule applications

The following products are not currently supported:

* xref:api-manager::analytics-landing-page.adoc[Anypoint Analytics]
* xref:monitoring::index.adoc[Anypoint Monitoring]
* xref:mq::index.adoc[Anypoint MQ]
* xref:anypoint-security::index.adoc[Anypoint Security]
* xref:visualizer::index.adoc[Anypoint Visualizer]
* xref:data-gateway::index.adoc[API Data Gateway]

For a detailed list of components and support information for each component by control plane, refer to the xref:general::intro-platform-hosting#support-matrix-for-control-plane-hosting-options[Support Matrix for Control Plane Hosting Options].

== See Also

* xref:gov-cloud::gov-cloud-security.adoc[Security in Government Cloud]
* xref:mule-runtime::fips-140-2-compliance-support.adoc[FIPS 140-2 Compliance Support]
