= Configure the Mule Runtime to Connect to MuleSoft Government Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To use Mule runtime engine (Mule) within MuleSoft Government Cloud, you must redefine the configuration properties that enable Mule runtime engine to point to MuleSoft Government Cloud. You must also provide the client ID and client secret of the environment belonging to your organization.

By default, Mule runtime engine is configured to point to the US control plane. If you do not override these properties, the API gateway capability of Mule runtime engine is disabled in MuleSoft Government Cloud.

The properties you must override depend on the version of Mule runtime engine you are using: Mule 4.0 or Mule 3.x.

== Configure Mule 4.0

You can configure Mule runtime engine (Mule) using `wrapper.conf`, the command line, or CloudHub.

=== wrapper.conf

To configure Mule runtime engine using the `wrapper.conf` file, modify the following properties, replacing `<n>` with an integer value that is unique within `wrapper.conf`:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://gov.anypoint.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.gov.anypoint.mulesoft.com
----

=== Command Line

To configure Mule runtime engine from the command line, use the following options when starting Mule. Note that `./` only applies to Unix environments.

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
-M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.gov.anypoint.mulesoft.com
----

=== CloudHub

When deploying to CloudHub, include the following properties in the Properties tab:

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.base_uri=https://gov.anypoint.mulesoft.com
anypoint.platform.analytics_base_uri=https://analytics-ingest.gov.anypoint.mulesoft.com
----

== Configure Mule 3.x

You can configure Mule runtime engine (Mule) using `wrapper.conf`, the command line, or CloudHub.

=== wrapper.conf

To configure the `wrapper.conf` file, modify the following properties, replacing `<n>` with an integer value that is unique within `wrapper.conf`:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.platform_base_uri=https://gov.anypoint.mulesoft.com/apiplatform
wrapper.java.additional.<n>=-Danypoint.platform.coreservice_base_uri=https://gov.anypoint.mulesoft.com/accounts
wrapper.java.additional.<n>=-Danypoint.platform.contracts_base_uri=https://gov.anypoint.mulesoft.com/apigateway/ccs
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.gov.anypoint.mulesoft.com
----

=== Command Line

To configure Mule runtime engine from the command line, use the following options when starting Mule. Note that `./` only applies to Unix environments.

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform -M-Danypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts -M-Danypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs -M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

=== CloudHub

When deploying to CloudHub, you must add the following information and enable the autodiscovery feature in the Properties tab. 

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.platform_base_uri=https://gov.anypoint.mulesoft.com/apiplatform
anypoint.platform.coreservice_base_uri=https://gov.anypoint.mulesoft.com/accounts
anypoint.platform.contracts_base_uri=https://gov.anypoint.mulesoft.com/apigateway/ccs
anypoint.platform.analytics_base_uri=https://analytics-ingest.gov.anypoint.mulesoft.com
----
