= Set up Your Government Cloud Account
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: gov-cloud-runtime-configuration.adoc

After you set up your account, Government Cloud works with your identity provider (IdP) to enable single sign-on (SSO) for users in your agency. Instead of using the Anypoint Platform sign-in page, your users sign in to the SSO system to access Anypoint Platform.

When you purchase Government Cloud, your Customer Success Manager sends you onboarding instructions and access to the https://help.mulesoft.com[MuleSoft Help Center].

To configure your IdP to work with Government Cloud:

. Verify that you have access to the Support Portal.
+
If not, contact your Customer Success Manager for credentials.
. In the Support Portal, click *Create New Case*.
. Enter your Support Center credentials and click *Log in*.
. Request to configure the connection to your external identity provider for your organization to enable SSO.
. Provide the required information about your IdP and any additional information, if applicable.
+
For the required information, see the documentation that applies to the SSO standard you use:

** xref:access-management::conf-openid-connect-task.adoc[OpenID Connect]
** xref:access-management::managing-users.adoc[SAML]

Using the information you provide, MuleSoft Support configures the connection to your IdP to enable SSO for your organization.

[IMPORTANT]
Government Cloud does not support the configuration of local users, for which usernames and encrypted passwords are stored outside of Government Cloud.
