= About Government Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

MuleSoft Government Cloud is a secure, FedRAMP-compliant deployment environment that enables government agencies to use Anypoint Platform in the cloud.

Your agency might already use Anypoint Platform on-premises to build applications. With Government Cloud, you can leverage the integration platform as a service (iPaaS) to reduce the infrastructure and management costs associated with legacy on-premises integration.

With MuleSoft managing the Anypoint Platform infrastructure, your IT teams can focus on designing integrations. You can manage and monitor all government integration assets from a single secure, cloud-based management console.

[IMPORTANT]
MuleSoft Government Cloud deployment permits deployment of Mule runtime engines into an on-premises environment (standalone Mules). Standalone Mules, and
MuleSoft support for standalone Mules, are outside the scope of FedRAMP. You are solely responsible for ensuring that all data shared with Salesforce complies
with any and all data and information protection policies, requirements, and standards. Review the MuleSoft System Security Plan for FedRAMP scope.

== See Also

* xref:gov-cloud::gov-cloud-features.adoc[Features Included in Government Cloud]
* https://marketplace.fedramp.gov/#/product/mulesoft-government-cloud?sort=productName[MuleSoft Government Cloud FedRAMP Authorization]
